var waitForjQuery = setInterval(function() {
	if (typeof jQuery != 'undefined') {

		jQuery(".page-warranty button:contains('Shop Our Protection Plans')").parents('.py-5').addClass('custHomeWarrantyPlanControl');

		if(jQuery('.custHomeWarrantyPlanControl').length > 0 && jQuery('.custWarrantyWraperControl').length == 0){
			jQuery('<section class="custWarrantyWraperControl"><div class="container"><h2>The ARW Home Warranty Difference<span>With Plans Built To Fit Your Needs &amp; Budget</span></h2><div class="warrantyPlanMainBoxControl"><div class="custWarrantyContainerControl"><div class="row"><div class="col-md-6"><div class="custImgBoxControl"><img src="https://growth-hit.s3.us-west-2.amazonaws.com/ARW/guaranteed_protection.png" class="desk"> <img src="https://growth-hit.s3.us-west-2.amazonaws.com/ARW/guaranteed_protection_mob.png" class="mob" alt=""></div></div><div class="col-md-6"><div class="warrantyContentControl"><h3><span>Guaranteed Protection</span>Feel Confident and Be in Control of Your Home</h3><ul><li>Our plans cover major appliances and systems you use every day, and if we can’t repair an item, we’ll replace it.</li><li>Choose from our network of qualified technicians, saving you time.</li></ul><div class="btnWraper"><a href="https://arwhome.com/plans-comparison" class="custBtn">Get Coverage Now</a></div></div></div></div><div class="row reverse"><div class="col-md-6"><div class="custImgBoxControl"><img src="https://growth-hit.s3.us-west-2.amazonaws.com/ARW/one_call_away.png" class="desk"> <img src="https://growth-hit.s3.us-west-2.amazonaws.com/ARW/one_call_away_mob.png" class="mob"></div></div><div class="col-md-6"><div class="warrantyContentControl"><h3><span>Only One Call Away</span>Around the Clock Support</h3><ul><li>24/7 365 Customer Protection Support</li><li>Emergency Services for critically urgent issues</li></ul><div class="btnWraper"><a href="https://arwhome.com/plans-comparison" class="custBtn">Get 24/7 Protection</a></div></div></div></div><div class="row"><div class="col-md-6"><div class="custImgBoxControl"><img src="https://growth-hit.s3.us-west-2.amazonaws.com/ARW/smartway_control.png" class="desk"> <img src="https://growth-hit.s3.us-west-2.amazonaws.com/ARW/smartway_control_mob.png" class="mob"></div></div><div class="col-md-6"><div class="warrantyContentControl"><h3><span>Smart Way to Control Unexpected Costs</span>Complete Home Protection Plan</h3><ul><li>Safeguard yourself from suprise breakdowns and repair costs</li><li>Exclusive member discounts & deals</li><li>Plans built to fit your needs & budget</li></ul><div class="btnWraper"><a href="https://arwhome.com/plans-comparison" class="custBtn">Start Saving Money Now</a></div></div></div></div></div></div></div></section>').insertAfter('.custHomeWarrantyPlanControl');
		}

		clearInterval(waitForjQuery);
	}
}, 50);